# Generated by Django 4.2.2 on 2024-02-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reportedposts',
        ),
    ]
