# Generated by Django 4.2.2 on 2024-02-12 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_remove_post_reported_by_users_reportedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reported_by_users',
            field=models.ManyToManyField(blank=True, related_name='reported_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
