# Generated by Django 4.2.2 on 2024-01-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
