# Generated by Django 4.2.2 on 2024-02-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_reported_by_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reported_by_users',
        ),
    ]
