# Generated by Django 4.2.2 on 2024-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_storedotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='StoredOTP',
        ),
    ]
